config/routes.rb
Rails.application.routes.draw do
  resources :special_deposits, except: [:index]

  resources :messages, only: [:create]

  get 'pages/index'
  get '/ping', to: 'pages#ping'

  root 'pages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :email, :from, :message, presence: true

  default_scope ->(){order('created_at DESC')}
end

app/models/special_deposit.rb
class SpecialDeposit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to root_path + '#leave-a-message'
    else
      render text: "<div class='error'> #{@message.errors.inspect} </div>", :layout => false, :status => :unprocessable_entity
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message, :from, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    Rails.logger.info "host: #{request.host}"
    Rails.logger.info "params: #{request.params.inspect}"
    @message = Message.new
    @messages = Message.all
  end

  def ping
    render text: 'pong'
  end
end

app/controllers/special_deposits_controller.rb
class SpecialDepositsController < ApplicationController
  before_action :set_special_deposit, only: [:show, :edit, :update, :destroy]
  before_filter :forbid_if_not_yours, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    reset_session
    session[:my_deposits] ||= []
    @special_deposit = SpecialDeposit.new
  end

  def edit
  end

  def create
    @special_deposit = SpecialDeposit.new(special_deposit_params)

    if @special_deposit.save
      session[:my_deposits] << @special_deposit.id
      redirect_to @special_deposit, notice: 'Special deposit was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @special_deposit.update(special_deposit_params)
        format.html { redirect_to @special_deposit, notice: 'Special deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @special_deposit }
      else
        format.html { render :edit }
        format.json { render json: @special_deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @special_deposit.destroy
    respond_to do |format|
      format.html { redirect_to special_deposits_url, notice: 'Special deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_special_deposit
      @special_deposit = SpecialDeposit.find(params[:id])
    end

    def special_deposit_params
      params.require(:special_deposit).permit(:from, :message, :value)
    end

    def forbid_if_not_yours
      head '404' unless session[:my_deposits].detect {|i| i == @special_deposit.id}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def in_chinese?
		%w(zh zh-cn).include? I18n.locale.to_s.downcase
	end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def countdown_from(date_string)
    (Date.parse(date_string) - Date.current).to_i
  end
end

app/helpers/special_deposits_helper.rb
module SpecialDepositsHelper
end

app/views/layouts/application.html.slim
doctype html
/![if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7"
/![if IE 7] <html class="no-js lt-ie9 lt-ie8"
/![if IE 8] <html class="no-js lt-ie9"
/! [if gt IE 8]><!
html.no-js
  /! <![endif]
  head
    meta charset="utf-8" /
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" /
    title Mei and Thi
    meta content=("Welcome to the wedding website for Mei and Thi's Big Day!") name="description" /
    meta content="width=device-width,initial-scale=1.0" name="viewport" /
    /! For iPhone 4 with high-resolution Retina display:
    link href="/apple-touch-icon-114x114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114" /
    /! For first-generation iPad:
    link href="/apple-touch-icon-72x72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72" /
    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    link href="/apple-touch-icon-precomposed.png" rel="apple-touch-icon-precomposed" /
    link href="/favicon.ico?v=1" rel=("shortcut icon") /
    / link href="css/normalize.min.css" rel="stylesheet" /
    / link href="assets/main-1.6.css" rel="stylesheet" /
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    - if in_chinese?
      = stylesheet_link_tag    'custom_zh'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'vendor/modernizr-2.6.2-respond-1.1.0.min.js'
    = csrf_meta_tags

body
  /![if lt IE 7]
    | <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p
  /
    | **************************************************************************************************
    | Template and base design by Bradley - https://github.com/bmgdev/responsive-wedding
    | ****************************************************************************************************

  - content = yield :bg_picture
  - if content.empty?
    picture#bg-image
      source media="(min-width: 768px)" srcset="/img/background.jpg"
      source media="(min-width: 320px)" srcset="/img/background-mobile.jpg"
      img src="/img/background.jpg" alt="mei_and_thi"
  - else
    = raw content
  #bg-container
    .header-container
      #heading.wrapper.clearfix
        nav#nav
          ul
            li= link_to I18n.t('views.pages.index.html.slim.home'), root_path
            = yield :extra_menus
            li= link_to "?locale=pt" do
              = image_tag '/img/Brazil-Flag-icon.png', class: :flag, alt: 'Português', title: 'Português'
            li= link_to "?locale=zh" do
              = image_tag '/img/China-Flag-icon.png', class: :flag, alt: '中文', title: '中文'
            li= link_to "?locale=en" do
              = image_tag '/img/United-Kingdom-flag-icon.png', class: :flag, alt: 'English', title: 'English'
    .main-container
      .main.wrapper.clearfix
        = yield
        div style=("height: 300px")
      /! #main
    /! #main-container
  /! #bg-container

  = javascript_include_tag 'vendors.js', 'data-turbolinks-track' => true
  = javascript_include_tag 'main-1.6.js', 'data-turbolinks-track' => true
  / javascript:
    | var _gaq = _gaq || [];
    | _gaq.push(['_setAccount', 'UA-XXXXXXX-XX']);
    | _gaq.push(['_trackPageview']);

    | (function() {
      | var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      | ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      | var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    | })();

app/views/messages/_form.html.slim
= form_for @message do |f|
  .field
    = f.label :from, "#{I18n.t('views.pages.index.html.slim.from_field')}: "
    = f.text_field :from, required: true
  .field
    = f.label :message, "#{I18n.t('views.pages.index.html.slim.message_field')}: "
    = f.text_area :message, required: true
  .field
    = f.label :email, "#{I18n.t('views.pages.index.html.slim.email_field')}: "
    = f.text_field :email, type: 'email', required: true
  .actions = f.submit I18n.t('views.pages.index.html.slim.send'), class:'button'

app/views/messages/_message.html.slim
.message
  .from= message.from
  .hr-t
  .hr-b
  pre.body= message.message

app/views/pages/index.html.slim
- content_for :extra_menus do
  li
    a href="#brideandgroom"= I18n.t('views.pages.index.html.slim.the_bride__groom')
  li
    a href="#wedding"= I18n.t('views.pages.index.html.slim.wedding')
  li
    a href="#gift-list"= I18n.t('views.pages.index.html.slim.gift_list')
  li
    a href="#leave-a-message"= I18n.t('views.pages.index.html.slim.leave_a_message')


header
  #introtext
    span.head-mei= I18n.t('views.pages.index.html.slim.mei__thiago')
    .date= I18n.t('views.pages.index.html.slim.date')
    .countdown= I18n.t('views.pages.index.html.slim.countdown', days: countdown_from(I18n.t('views.pages.index.html.slim.date_raw')))
.clearfix

section#brideandgroom.clearfix
  h1=raw I18n.t('views.pages.index.html.slim.the_bride_and_groom_title')
  .column.half
    h2=I18n.t('views.pages.index.html.slim.mei')
    p.clearfix
      img.thumb alt="Mei" src="img/meiThumb.jpg" /
      =raw I18n.t('views.pages.index.html.slim.mei_description')
  /! end column
  .column.half
    h2= I18n.t('views.pages.index.html.slim.thiago')
    p.clearfix
      img.thumb alt="Thi" src="img/thiThumb.jpg" /
      =raw I18n.t('views.pages.index.html.slim.thi_description')
  /! end column
  .clearfix
  - unless in_chinese?
    .column.full
      .hr-t
      .hr-b
    .column.full
      h1=I18n.t('views.pages.index.html.slim.our_path')
      picture.responsive-image.map_how_we_met
        source media="(min-width: 768px)" srcset="/img/convite_finalizado.jpg"
        source media="(min-width: 320px)" srcset="/img/convite_finalizado-mobile.jpg"
        img src="img/convite_finalizado.jpg" alt="mapa"
    /! end column

section#wedding.clearfix
  .column.left
    h1= I18n.t('views.pages.index.html.slim.wedding_title')
    p
      strong= I18n.t('views.pages.index.html.slim.wedding_place')
      br/
      = I18n.t('views.pages.index.html.slim.wedding_address_line_1')
      br/
      = I18n.t('views.pages.index.html.slim.wedding_address_line_2')
      br/
      br/
      = I18n.t('views.pages.index.html.slim.cerimony_date')
      br/
      = I18n.t('views.pages.index.html.slim.cerimony_time')
  #party-address.column.right
  - if in_chinese?
    a href="http://j.map.baidu.com/_pwF4"
      img.column.left alt="map-xianyang" src="img/map-xianyang.jpg"
  - else
    h1= I18n.t('views.pages.index.html.slim.party_title')
    p
      strong= I18n.t('views.pages.index.html.slim.party_place')
      br/
      = I18n.t('views.pages.index.html.slim.party_address_line_1')
      br/
      = I18n.t('views.pages.index.html.slim.party_address_line_2')
      br/
      br/
      = I18n.t('views.pages.index.html.slim.party_desc')
    .clearfix
    .column.full
      .hr-t
      .hr-b
      .overlay onClick="style.pointerEvents='none'"
      iframe src="https://www.google.com/maps/d/u/0/embed?mid=zFZS05FuOUp8.kS1YN0bMBK7I" width="100%" height="480"

section#gift-list.clearfix
  h1= I18n.t('views.pages.index.html.slim.gift_list_title')
  .column.full
    p=raw I18n.t('views.pages.index.html.slim.gift_list_desc')
    - unless in_chinese?
      ul.links
        li#gift-list-link= link_to I18n.t('views.pages.index.html.slim.gift_list_link'), "https://sites.icasei.com.br/meiethi"
        li#special-message-link= link_to I18n.t('views.pages.index.html.slim.special_message_link'), new_special_deposit_path

section#leave-a-message.clearfix
  h1= I18n.t('views.pages.index.html.slim.leave_a_message_title')
  .column.full
    p= I18n.t('views.pages.index.html.slim.leave_a_message_desc')
    = render partial: 'messages/form'
  #messages
    = render @messages
  .clearfix

app/views/special_deposits/_form.html.slim
.account-details
  p
    strong Nome:
    span Thiago Rodrigues Colucci
  p
    strong Banco:
    span 399 - HSBC
  p
    strong Conta Corrente:
    span 03498 - 02
  p
    strong Agência:
    span 0252
  p
    strong CPF:
    span 089.369.456-88

app/views/special_deposits/edit.html.slim
section.special-deposit
  h1= I18n.t('views.special_deposits.edit.html.slim.editando_depsito_especial')

  == render 'form'

  = link_to 'Visualizar', @special_deposit

app/views/special_deposits/new.html.slim
- content_for :bg_picture do
  picture#bg-image
    source media="(min-width: 768px)" srcset="/img/bg-thanks.jpg"
    source media="(min-width: 320px)" srcset="/img/bg-thanks-mobile.jpg"
    img src="/img/bg-thanks.jpg" alt="THANKS! =)"

section.special-deposit
  h1= I18n.t('views.special_deposits.new.html.slim.depsito_especial')

  == render 'form'

app/views/special_deposits/show.html.slim
- content_for :bg_picture do
  picture#bg-image
    source media="(min-width: 768px)" srcset="/img/bg-thanks.jpg"
    source media="(min-width: 320px)" srcset="/img/bg-thanks-mobile.jpg"
    img src="/img/bg-thanks.jpg" alt="THANKS! =)"

section.special-deposit
  p.thanks
    = I18n.t('views.special_deposits.show.html.slim.muito_obrigado')

  p.info
    = I18n.t('views.special_deposits.show.html.slim.mensagem_postada')

  .message
    .from
      strong= @special_deposit.from
    .hr-t
    .hr-b

    pre.body
      = @special_deposit.message
    .value-wrapper
      span.value
        strong= "#{I18n.t('views.special_deposits.show.html.slim.valor_para_o_depsito')}: "
        = @special_deposit.value

  = link_to 'Editar', edit_special_deposit_path(@special_deposit)